<?php

/**
 * @file
 * Contains studio_photodesk_screens.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function warehouse_checkin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the studio_photodesk_screens module.
    case 'help.page.warehouse_checkin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module holds all screens which are required for warehouse operations.') . '</p>';
      return $output;

    default:
  }
}


function warehouse_checkin_theme($existing, $type, $theme, $path) {
  return array(
    'checkin' => array(
      'variables' => array('container' => array(), 'product_identifier' => NULL, 'product_block' => array()),
      'template' => 'checkin-view'
    ),
    'view_container' => array(
      'variables' => array(
        'container' => array(),
        'products' => array(),
        'test' => NULL,
        'grouped_concepts' => array(),
        'unmapped_products' => array(),
      ),
    ),
    'view_all_containers' => array(
      'variables' => array(
        'results' => array (

      ),
    ),
    ),
  );
}

/*
 *  Implements hook_form_alter().
 */
function warehouse_checkin_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //todo : move js code here , to change label of node title for container content type.
  if ($form_id == 'node_container_form') {}
}
