studiobridge_global_settings.studio_settings_form:
  title: 'Studio settings'
  route_name: studiobridge_global_settings.studio_settings_form
  description: 'StudioBridge settings page'
  parent: system.admin_config_system
  weight: 99

