
studiobridge_global_settings.studio_settings_form:
  path: '/admin/config/studiobridge_global_settings/studiosettings'
  defaults:
    _form: '\Drupal\studiobridge_global_settings\Form\StudioSettingsForm'
    _title: 'StudioSettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

