resources:
  'entity:node':
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
    POST:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
    PATCH:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  open_sessions_rest_resource:
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  individual_session_rest_resource:
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  'entity:file':
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
    POST:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
    DELETE:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
    PATCH:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  studio_live_image_container_rest_resource:
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  'entity:block':
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  file_name_rest_resource:
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  drop_product_post:
    POST:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  time_session_product_post:
    POST:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
  warehouse_operations:
    POST:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - basic_auth
        - cookie
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
