<?php

/**
 * @file
 * Contains studio_photodesk_screens.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function studio_photodesk_screens_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the studio_photodesk_screens module.
    case 'help.page.studio_photodesk_screens':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module holds all screens which are required for Photo desk operations.') . '</p>';
      return $output;

    default:
  }
}

/*
 * Implements hook_theme().
 */
function studio_photodesk_screens_theme($existing, $type, $theme, $path) {
  return array(
    'view_session' => array(
      'variables' => array(
        'session' => NULL,
        'mapped_products' => NULL,
        'unmapped_products' => NULL,
        'grouped_concepts' => NULL,
        'session_users' => NULL,
        'total_images' => NULL,
        'period' => NULL,
        'session_time' => NULL,
        'period_chart' => NULL,
        'mapped_dropped_products' => NULL,
        'unmapped_dropped_products' => NULL,
        'drops' => NULL,
        'models' => NULL
      ),
    ),
    'view_product' => array(
      'variables' => array('product' => NULL, 'images'=> NULL),
    ),
      'view_all_sessions' => array(
          'variables' => array('results' => NULL),
      ),
      'view_all_products' => array(
        'variables' => array(
          'results' => array (),
      ),
      ),
      'view_dashboard' => array(
        'variables' => array(
          'results' => array (),
          'mapped' => array (),
          'unmapped' => array (),
      ),
      ),
      'view_all_models' => array(
        'variables' => array(
          'results' => array (),
          'mapped' => array (),
          'unmapped' => array (),
      ),
      ),
      'view_pdp' => array(
        'variables' => array('product' => NULL, 'images'=> NULL),
    ),
  );
}
